<a href="https://colab.research.google.com/github/tu22014/Chapter2/blob/main/Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ライブラリのインポート
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mp1
import seaborn as sns
%matplotlib inline

#少数第3位まで表記
%precision 3

#(2-1)配列の作成
data = np.array([9,2,3,4,10,6,7,8,1,5])

#(2-2)データの型　int(符号付きの整数),uint(符号なしの整数),float(浮動小数点数),bool(真偽値)
data.dtype

#(2-3)次元数と要素数
print('次元数:',data.ndim)
print('要素数:',data.size)

#(2-4)すべての要素に対する計算
#Numpyでは配列に対して*nですべての要素をn倍できる。
#それぞれの数字を係数倍（ここでは５倍）
data * 5
#それぞれの要素同士での演算
print('掛け算：', np.array([1,2,3,4,5,6,7,8,9,10]) * np.array([10,9,8,7,6,5,4,3,2,1]))
print('累乗:', np.array([1,2,3,4,5,6,7,8,9,10]) ** 2)
print('割り算:', np.array([1,2,3,4,5,6,7,8,9,10]) / np.array([10,9,8,7,6,5,4,3,2,1]))

#(2-5)並び替え（ソート）
#デフォルトでは昇順（小から大）
print('そのまま:', data)
data.sort()
print('ソート後:', data)
#降順はdata[::-1].sort()のようにスライスを使います。[n:m:s]は、「n番目からm-1番目をsずつ飛ばして取り出す」という意味になります。
#[::-1]は、「小尾から1つずつ取り出す」という意味になります。
data[::-1].sort()
print('降順にソート後:', data)

#(2-6)最小、最大、合計、積上の計算
#最小値
print('Min:', data.min())
#最大値
print('Max:', data.max())
#合計
print('Sum:', data.sum())
#積み上げ
print('Cum:', data.cumsum())
#積み上げ割合
print('ratio:', data.cumsum() / data.sum())

#(3)乱数
#(3-1)乱数のシード
#乱数は疑似乱数で数式によってランダムな値を作り出します。
#そのランダムな値の初期値をシードといい、random.seedを使って指定できます。
random.seed(0)

#(3-2)乱数の発生
#正規分布　（平均0,分散1）の乱数を10個発生
rnd_data = random.randn(10)
print('乱数10個の配列:', rnd_data)
random.seed(5)
rnd_data2 = random.randn(10)
print('シード5での乱数10個の配列:', rnd_data2)

#(3-3)データのランダムな抽出
#抽出対象データ
data = np.array([9,2,3,4,10,6,7,8,1,5])

#ランダム抽出
#10個を抽出（重複あり、復元抽出）
print(random.choice(data, 10))
#10個を抽出（重複なし、非復元抽出）
print(random.choice(data, 10, replace = False))




次元数: 1
要素数: 10
掛け算： [10 18 24 28 30 30 28 24 18 10]
累乗: [  1   4   9  16  25  36  49  64  81 100]
割り算: [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]
そのまま: [ 9  2  3  4 10  6  7  8  1  5]
ソート後: [ 1  2  3  4  5  6  7  8  9 10]
降順にソート後: [10  9  8  7  6  5  4  3  2  1]
Min: 1
Max: 10
Sum: 55
Cum: [10 19 27 34 40 45 49 52 54 55]
ratio: [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]
乱数10個の配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]
シード5での乱数10個の配列: [ 0.441 -0.331  2.431 -0.252  0.11   1.582 -0.909 -0.592  0.188 -0.33 ]
[ 2 10  7  3  5  5  5  5  2  3]
[ 2  5  4 10  1  3  6  7  9  8]


In [ ]:
#ライブラリのインポート
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mp1
import seaborn as sns
%matplotlib inline

#少数第3位まで表記
%precision 3

#(4)行列
np.arange(9)
array1 = np.arange(9).reshape(3,3)
print(array1)

#1行目
array1[0,:]
#1列目
array1[:,0]

array2 = np.arange(9,18).reshape(3,3)
print(array2)

#(4-1)行列の演算
#行列の積
np.dot(array1,array2)

#要素どうしの積
array1 * array2

#(4-2)要素が0や1の行列を作る
print(np.zeros((2,3), dtype = np.int64))
print(np.ones((2,3), dtype = np.float64))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#(2-3-1)Scipyのライブラリのインポート
#線形代数用のライブラリ
import scipy.linalg as linalg
#最適化計算（最小値）用の関数
from scipy.optimize import minimize_scalar

#(2-3-2)行列計算
#(2-3-2-1)行列式と逆行列の計算
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

#行列式
print('行列式')
print(linalg.det(matrix))

print('\n')
#逆行列
print('逆行列')
print(linalg.inv(matrix))

print('\n')
print(matrix.dot(linalg.inv(matrix)))

print('\n')
#(2-3-2-2)固有値と固有ベクトル
#固有値と固有ベクトル
eig_value, eig_vector = linalg.eig(matrix)

print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)

print('\n')
#(2-3-3)ニュートン法
#(2-3-3-1)方程式の解を求める
#関数の定義
def my_function(x):
  return (x**2 + 2*x + 1)
#ニュートン法の読み込み
from scipy.optimize import newton
#計算実行
print(newton(my_function,0))

print('\n')
#(2-3-3-2)最小値を求める
#計算実行
print(minimize_scalar(my_function, method = 'Brent'))

行列式
-4.0


逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[ 0.577  0.816  0.408]
 [ 0.577 -0.408 -0.816]
 [ 0.577 -0.408  0.408]]


-0.9999999852953906


     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002


In [27]:
#ライブラリのインポート
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mp1
import seaborn as sns
%matplotlib inline

#少数第3位まで表記
%precision 3

#(2-4)Pandasの基礎
#(2-4-1)Pandasのライブラリのインポート
from pandas import Series, DataFrame

#(2-4-2)Seriesの使い方
#　Series
sample_pandas_data = pd.Series([0,10,20,30,40,50,60,70,80,90])
print(sample_pandas_data)

# indexをアルファベットでつける
sample_pandas_index_data = pd.Series([0,10,20,30,40,50,60,70,80,90], index=['a','b','c','d','e','f','g','h','i','j'])
print(sample_pandas_index_data)

print('データの値', sample_pandas_index_data.values)
print('インデックスの値', sample_pandas_index_data.index)

#(2-4-3) DataFrameの使い方
attri_data1 = {'ID':['100','101','102','103','104'],
               'City':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
               'Birth_year':[1990,1989,1992,1897,1982],
               'Name':['Hiroshi','Akiko','Yuki','Satoru','Steve']}
attri_data_frame1 = DataFrame(attri_data1)
print(attri_data_frame1)

attri_data_frame_index1 = DataFrame(attri_data1,index=['a','b','c','d','e'])
print(attri_data_frame_index1)

#(2-4-3-1) Jupyter環境におけるデータ表示
#printを使わなくてもSeriesやDataFrameオブジェクトは表示できる
attri_data_frame_index1

#(2-4-4)　行列操作
#(2-4-4-1)　転置
attri_data_frame1.T

#(2-4-4-2)特定列のみを取り出す
#列名の指定（1つの場合）
attri_data_frame1.Birth_year
#列名の指定（複数の場合）
attri_data_frame1[['ID','Birth_year']]

#(2-4-5)データの抽出
#条件（フィルター）
attri_data_frame1[attri_data_frame1['City'] == 'Tokyo']

attri_data_frame1['City'] == 'Tokyo'

#条件（フィルター、複数の値）
attri_data_frame1[attri_data_frame1['City'].isin(['Tokyo','Osaka'])]

attri_data_frame1[attri_data_frame1['Birth_year'].isin([1990,1989])]

#(2-4-6)データの削除と結合
#(2-4-6-1)列や行の削除
attri_data_frame1.drop(['Birth_year'], axis = 1)

#(2-4-6-2)データの結合
#別データの準備
attri_data2 = {'ID':['100','101','102','105','107'],
               'Math':[50,43,33,76,98],
               'English':[90,30,20,50,30],
               'Sex':['M','F','F','M','M']}
attri_data_frame2 = DataFrame(attri_data2)
attri_data_frame2

#データのマージ
pd.merge(attri_data_frame1,attri_data_frame2)

#(2-4-7)集計
#データのグループの集計
attri_data_frame2.groupby('Sex')['Math'].mean()

#(2-4-8)値のソート
#データの準備
attri_data2 = {'ID':['100','101','102','103','104'],
               'City':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
               'Birth_year':[1990,1989,1992,1997,1982],
               'Name':['Hiroshi','Akiko','Yuki','Satoru','Steve']}
attri_data_frame2 = DataFrame(attri_data2)
attri_data_frame_index2 = DataFrame(attri_data2,index=['e','b','a','d','c'])
attri_data_frame_index2

#indexによるソート
attri_data_frame_index2.sort_index()

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64
a     0
b    10
c    20
d    30
e    40
f    50
g    60
h    70
i    80
j    90
dtype: int64
データの値 [ 0 10 20 30 40 50 60 70 80 90]
インデックスの値 Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')
    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1897   Satoru
4  104     Tokyo        1982    Steve
    ID      City  Birth_year     Name
a  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
c  102     Kyoto        1992     Yuki
d  103  Hokkaido        1897   Satoru
e  104     Tokyo        1982    Steve


ID      City  Birth_year     Name
a  102     Kyoto        1992     Yuki
b  101     Osaka        1989    Akiko
c  104     Tokyo        1982    Steve
d  103  Hokkaido        1997   Satoru
e  100     Tokyo        1990  Hiroshi

In [ ]:
practice2_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50])
print('合計:', practice2_1.sum())

合計: 1275
